import { readFile } from "node:fs/promises";
import { parseProject } from "../lib/projectSerialization.js";
import { validateProject } from "../lib/validate.js";
import { exportRuntimePackage } from "../lib/exportRuntime.js";
import { exportInkProject, exportSinpoGameData } from "../lib/exportFormats.js";
import { createCanonEditSuggestion } from "../lib/projectMutations.js";

const fixturePath = new URL("../examples/worldnotion-bridge-demo-project.json", import.meta.url);
let project = parseProject(await readFile(fixturePath, "utf8"));
project = createCanonEditSuggestion(project, project.canonRefs[0]?.id ?? "").project;
const findings = validateProject(project).filter((finding) => finding.severity === "error");

if (findings.length) {
  throw new Error(`Expected demo project to validate without errors, got ${findings.length}.`);
}

if (!project.dataClasses?.some((dataClass) => dataClass.id === "class:KnowledgeEntry")) {
  throw new Error("Expected normalized project to include the KnowledgeEntry data class.");
}

const runtimePackage = exportRuntimePackage(project);
const runtimeText = JSON.stringify(runtimePackage);
if (runtimeText.includes('"canvas"') || runtimeText.includes('"panels"')) {
  throw new Error("Runtime export must not include visual authoring state.");
}

if (!runtimeText.includes('"canonEditSuggestions"') || !runtimeText.includes('"worldnotion-review-required"')) {
  throw new Error("Expected runtime metadata to include safe WorldNotion edit suggestions.");
}

if (!runtimePackage.nodes.every((node) => Array.isArray(node.canonRefDetails))) {
  throw new Error("Expected runtime nodes to include dynamic canon ref details.");
}

const inkExport = exportInkProject(project);
if ((!inkExport.files.length && !inkExport.diagnostics?.length) || !inkExport.files.every((file) => file.content.includes("Generated by Everend PathBranching"))) {
  throw new Error("Expected executable Ink or explicit blocking diagnostics for unsupported demo logic.");
}

const gameDataExport = exportSinpoGameData(project);
if (gameDataExport.format !== "sinpo-game-data" || gameDataExport.events.length !== project.events.length) {
  throw new Error("Expected SINPO GameData export to include all story events.");
}

console.log(
  JSON.stringify(
    {
      findings: findings.length,
      runtimeNodes: runtimePackage.nodes.length,
      inkFiles: inkExport.files.length,
      gameDataEvents: gameDataExport.events.length,
      dataClasses: project.dataClasses.length,
      canonEditSuggestions: project.canonEditSuggestions.length,
    },
    null,
    2,
  ),
);
