import type { BranchingProject } from "./domain.js";
import { exportInkProject } from "./exportFormats.js";
import { exportRuntimePackage } from "./exportRuntime.js";
import { validateProject } from "./validate.js";

export type EverendOfflineBundleFile = { path: string; content: string };

export function buildEverendOfflineBundle(project: BranchingProject, profileId = "sinpo-v0.1"): EverendOfflineBundleFile[] {
  const findings = validateProject(project);
  const validationReport = {
    specVersion: "0.1",
    tool: "Everend PathBranching",
    findings: findings.map((finding) => ({
      code: "missing_required_field",
      sourceCode: finding.code,
      severity: finding.severity,
      message: finding.message,
      nodeId: finding.id,
      field: finding.ref,
    })),
  };
  const runtimePackage = exportRuntimePackage(project);
  const ink = exportInkProject(project);
  const files: EverendOfflineBundleFile[] = [
    { path: "runtime-package.json", content: `${JSON.stringify(runtimePackage, null, 2)}\n` },
    { path: "sinpo-projection.json", content: `${JSON.stringify({ bundleVersion: "0.1", profileId, profileVersion: "0.1.0", projectId: project.projectId, storyId: project.storyId, integrationConfig: project.integrationConfig }, null, 2)}\n` },
    { path: "adapter-manifest.json", content: `${JSON.stringify({ adapterVersion: "0.1.0", profileId, projectId: project.projectId, storyId: project.storyId, revision: 0, entries: [] }, null, 2)}\n` },
    { path: "validation-report.json", content: `${JSON.stringify(validationReport, null, 2)}\n` },
  ];
  for (const file of ink.files) {
    const sequenceId = file.path.replace(/\.ink$/i, "");
    const sections = file.content.split(/^=== /m).slice(1);
    if (sections.length === 0) {
      files.push({ path: `Ink/${sequenceId}/sequence.ink`, content: file.content });
      continue;
    }
    for (const section of sections) {
      const knot = section.split(" ===", 1)[0].trim().replace(/[^A-Za-z0-9_.-]/g, "_") || "event";
      files.push({ path: `Ink/${sequenceId}/${knot}.ink`, content: `// Generated by Everend PathBranching\n=== ${section}` });
    }
  }
  return files;
}
